name: Publish canaray packages to npm

on:
  push:
    branches: [main]
    tags-ignore:
      - v** # We don't want this to run on release

jobs:
  build:
    if: github.repository == 'redwoodjs/redwood'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required because lerna uses tags to determine the version.
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Print node and yarn versions
        run: |
          node --version
          yarn --version
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Build
        run: yarn build

      - name: Run ESLint
        run: yarn lint
        env:
          CI: true

      - name: Run tests
        run: yarn test
        env:
          CI: true

      - name: Publish to npm
        run: |
          git describe
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ./tasks/framework-tools/.npmrc
          yarn framework publish:canary
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
